apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: docreg.eprocure.gov.pk/test:${BUILD_NUMBER}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 
      imagePullSecrets:
       - name: acr-auth
--- 
apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  type: NodePort
  selector:
    app: test1
  ports:
  - nodePort: 30163
      port: 8080 
      targetPort: 80
  

